$LOAD_PATH.unshift('lib')
require 'fileutils'
require 'oplss/bluebird'

desc 'Build the gem'
task :build do
  require 'rubygems/commands/build_command'
  Gem::Commands::BuildCommand.new.invoke(OPLSS::Bluebird::NAME)
end

desc 'Delete ephemeral files'
task :clean do
  FileUtils.rm_f(
    Dir.glob(%w[*.gem *.lock]),
    verbose: true
  )
end

# Default task
task default: %i[test]

begin
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new(:style)
rescue LoadError
  STDERR.puts('RuboCop not installed -- unable to invoke style tests')
end

desc 'Invoke the unit and style tests'
task test: %i[unit style]

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:unit)
rescue LoadError
  STDERR.puts('RSpec not installed -- unable to invoke unit tests')
end
